/**
 * prod-seed.ts — one-time production bootstrap
 * Creates an admin account + initial invite code in prod DynamoDB.
 * Run with: AWS_REGION=ap-east-1 DYNAMODB_TABLE_NAME=nanchang_main NODE_ENV=production pnpm --filter @nanchang/api run seed:prod
 * Delete after use.
 */

import * as crypto from 'crypto';
import * as bcrypt from 'bcryptjs';

import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, PutCommand, GetCommand } from '@aws-sdk/lib-dynamodb';

const REGION = process.env.AWS_REGION ?? 'ap-east-1';
const TABLE_NAME = process.env.DYNAMODB_TABLE_NAME ?? 'nanchang_main';

const DK = {
  userProfile: (sub: string) => ({ PK: `USER#${sub}`, SK: 'PROFILE' }),
  handleLock: (handle: string) => ({ PK: `HANDLE#${handle.toLowerCase()}`, SK: 'LOCK' }),
  invite: (code: string) => ({ PK: `INVITE#${code.toUpperCase()}`, SK: 'META' }),
};

function generateInviteCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const bytes = crypto.randomBytes(8);
  return Array.from(bytes)
    .map((b) => chars[b % chars.length])
    .join('');
}

async function main(): Promise<void> {
  const ddbRaw = new DynamoDBClient({ region: REGION });
  const db = DynamoDBDocumentClient.from(ddbRaw, {
    marshallOptions: { removeUndefinedValues: true },
  });

  const ADMIN_HANDLE = 'admin';
  const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD ?? 'Admin1234!';

  // Check if admin already exists
  const lockKey = DK.handleLock(ADMIN_HANDLE);
  const existing = await db.send(new GetCommand({ TableName: TABLE_NAME, Key: lockKey }));

  let adminSub: string;
  if (existing.Item) {
    adminSub = existing.Item.ownerSub as string;
    console.log(`Admin @${ADMIN_HANDLE} already exists (${adminSub}) — skipping account creation.`);
  } else {
    adminSub = crypto.randomUUID();
    const passwordHash = await bcrypt.hash(ADMIN_PASSWORD, 10);
    const now = new Date().toISOString();

    await db.send(
      new PutCommand({
        TableName: TABLE_NAME,
        Item: {
          ...DK.userProfile(adminSub),
          sub: adminSub,
          handle: ADMIN_HANDLE,
          displayName: 'Admin',
          role: 'admin',
          passwordHash,
          createdAt: now,
          updatedAt: now,
          disabled: false,
        },
        ConditionExpression: 'attribute_not_exists(PK)',
      }),
    );
    await db.send(
      new PutCommand({
        TableName: TABLE_NAME,
        Item: { ...lockKey, ownerSub: adminSub, createdAt: now },
      }),
    );
    console.log(`Created admin @${ADMIN_HANDLE} (sub: ${adminSub})`);
  }

  const inviteCode = generateInviteCode();
  const now = new Date().toISOString();
  await db.send(
    new PutCommand({
      TableName: TABLE_NAME,
      Item: {
        ...DK.invite(inviteCode),
        gsi1pk: 'INVITE_STATUS#active',
        gsi1sk: inviteCode,
        code: inviteCode,
        status: 'active',
        createdBy: adminSub,
        createdAt: now,
        updatedAt: now,
        note: 'Initial invite generated by prod-seed',
      },
    }),
  );

  console.log(`
─────────────────────────────────────
  Production seed complete!

  Admin login:
    Handle:   admin
    Password: ${ADMIN_PASSWORD}

  Initial invite code: ${inviteCode}
  Share with first family member.
─────────────────────────────────────
`);
}

main().catch((err) => {
  console.error('Prod seed failed:', err);
  process.exit(1);
});
